= About

== About

The 42ITY(TM) project promotes the global development, distribution and
adoption of the 42ITY(TM) platform as a next generation Data Center Service
Optimization enablement platform.

The goal is to serve developers, users and the entire data center ecosystem
by providing a set of shared resources to grow the adoption of 42ITy(TM) as
the only open source, next generation Data Center Service Optimization
enablement platform.

The initial 42ITY(TM) platform is a result of more than 3 years of R&D effort
by Eaton Corporation provided to the community.  While Eaton continues to
be a key contributor to 42ITy(TM), the community is already growing. Please
read the link:contributing.html[Contributor guide] to find out how you can
contribute.

Regular development team (in alphabetical order)
------------------------------------------------

- Lucas Bchini
- Guillaume Brialon
- Yves Clauzel
- Gerald Guillaume
- Vojtech Hejl
- Ekaterina Klimova
- Evgeny Klimov
- Jiři Kukačka
- Michal Marek
- Jean Perriault
- Arnaud Quette
- Jana Rapava
- Barbora Štepankova

Retired regular developers (in alphabetical order)
--------------------------------------------------

- Julio Bruno
- Alena Chernikava
- Tomas Halman
- Karol Hrdina
- Michal Hrušecky
- Hélder Loureiro
- Radomir Vrajik
- Michal Vyskočil

And extra thanks to members of other teams in Eaton Corporation and outside,
as well as to numerous non-developers involved in the project and the open
source ecosystems it builds upon, who have all contributed greatly to its
evolution (and keep doing it).
