= 42ITy Contributor guide

== 42ITy Contributor guide

There are many ways you can help make 42ITY(TM) better!

This guide will help answer common questions you may have during your first and
further contribution.

== License

The project 42ITy(TM) uses the
https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html[GNU General Public
License v2+] license. Refer to the LICENSE file available in each 42ITy(TM)
internal sub-projects.


== Contribution Process

The project 42ITy(TM) adheres to the
link:c4.html[C4 (Collective Code Construction Contract)] process for
contributions.

Please read this document if you are unfamiliar with it.


== Coding and documentation style guides

The project 42ITy(TM) uses:

* the link:class.html[CLASS (C Language Style for Scalability)] guide for code
style.
* the link:doc-recommendation.html[Documentation Recommendation] for
documentation style.

Please read these documents if you are unfamiliar with them.


== Developer Certification of Origin (DCO)

To make a good faith effort to ensure the criteria of the GPL License are met,
42ITy(TM) requires the Developer Certificate of Origin (DCO) process to be
followed.

The DCO is an attestation attached to every contribution made by every
developer. In the commit message of the contribution, the developer simply adds
a Signed-off-by statement and thereby agrees to the DCO, which you can find
below or at link:http://developercertificate.org/[Developer Certificate of Origin].

include::dco.asciidoc[]

[icon="./images/icons/important.png"]
IMPORTANT: 42ITy(TM) does not merge any pull requests made against a
42ITy-managed repository until each commit has been signed for the DCO.

=== Practical example of commit with DCO 

Applying the DCO is as simple as adding '--signoff' when doing a 'git commit':

----------------------------------------------------------------------------
git commit --signoff
----------------------------------------------------------------------------

This will add the 'Signed-off-by' line at the end of the commit log message. For
example:

----------------------------------------------------------------------------
commit af7daa6490a3b04ed1ae6921d5b701b9558feb2f
Author: John Doe <johndoe@some.org>
Date:   Thu Nov 17 13:45:21 2016 +0100

  Problem: there is a problem

  Solution: fix the problem

  Signed-off-by: John Doe <johndoe@some.org>

----------------------------------------------------------------------------


== Submitting issue 

Not every contribution comes in the form of code. Submitting, confirming, and
triaging issues is an important task for any project.

42ITy(TM) project uses GitHub to track all except security issues.

If it's possible please submit a minimal program that compiles and reproduces
or show the issue.

[icon="./images/icons/important.png"]
IMPORTANT: If you want to submit a security issue please contact the development
team using link:mailto:EatonIPCOpensource@Eaton.com[Eaton IPC Opensource]


== Further Reading

The Documentation section of the link:http://42ity.org[42ITy(TM) website] provides
some complementary technical information, such as:

* how to interact with 42ITy(TM) through the REST API
* how to create new agents for 42ITy(TM)

== Thanks and credits

A number of technical and documentation points in 42ITy(TM) are inspired from
ZeroMQ ones, created and led by Pieter Hintjens. The 42ITy(TM) team wants to
express its undying thanks to Pieter, for everything he did and his help to
create the foundations of the 42ITy(TM) project!

The 42ITy(TM) team also wants to thank the various projects used in the 42ITy(TM)
software stack, along with the Opensource Community in general. This project
would never have been possible without these!
