42ITy Contributing Policy
=========================
:Email:     EatonIPCOpensource@eaton.com
:Date:      2.12.2016
:Revision:  1.2

== License
This project uses the
https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html[GNU General Public
License v2+] license, see LICENSE file.

== Authors
The contributors are listed in AUTHORS file. You are responsible for adding
yourself to this file.

== Contribution process and Code style guide

Project 42ITy uses:

* https://rfc.zeromq.org/spec:42/C4/[C4 (Collective Code Construction
Contract)] process for contributions.
* https://rfc.zeromq.org/spec:21/CLASS/[CLASS (C Language Style for
Scalabilty)] guide for code style. 

Please read these documents if you are unfamiliar with it. 

=== Developer Certification of Origin (DCO)

To make a good faith effort to ensure the criteria of the GPL License are met,
42ITy requires the Developer Certificate of Origin (DCO) process to be followed.

The DCO is an attestation attached to every contribution made by every
developer. In the commit message of the contribution, the developer simply adds
a Signed-off-by statement and thereby agrees to the DCO, which you can find
below or at link:http://developercertificate.org/[Developer Certificate of Origin].

include::dco.asciidoc[]

42ITy does not merge any pull requests made against a 42ITy-managed repository
until each commit has been signed for the DCO, with two exceptions:
“Obvious Fixes” and pull requests made against the documentation repository

== Submitting issue 
42ITy project uses GitHub to track all except security issues.

If it's possible please submit a minimal program that compiles and reproduces
or show the issue.

If you want to submit a security issue please contact the development team
using link:mailto:EatonIPCOpensource@Eaton.com[Eaton IPC Opensource]

/////
@AQU: Add

<code>
== Feature request
If you have a feature request, this is an excellent place to start: https://feedback.42ity.org.
</code>

only when it's ready.
/////

== Thanks
This contributing policy is inspired by https://github.com/zeromq/czmq/blob/master/CONTRIBUTING.md[CZMQ contributing policy].

Our undying thanks goes to Pieter Hintjens. *Thank you, Pieter, for everything!*


