= Welcome to 42ITy!

== Our mission

The 42ITy(TM) project exists to provide the most open, flexible platform in the
industry for enabling data center service optimization, where active equipment
from multiple datacenter infrastructure solution vendors can be managed on a
common dashboard.

Proprietary, monolithic solutions for data center infrastructure management have
often failed to provide the expected customer value because they are too costly
to integrate & deploy in heterogeneous data center environments.

42ITy(TM) addresses these issues by providing an intuitive data center monitoring
platform based on a modern micro-services architecture with open REST APIs,
facilitating integration with existing solutions. And best of all, it is open
source! This enables data center operators and data center ecosystem solution
partners to provide a seamless monitoring experience even in the most
heterogeneous environments via a common framework and APIs.


== Recent Updates

- May 27th, 2021: Released IPM2 Editions version 2.3.0 as x86_64 OVA virtual appliance and software update packages
  * More details at https://github.com/42ity/release-note/blob/release/IPM-2.3.0/ipm/2.3.0.md
- February 3rd, 2021: Released IPM2 Editions version 2.2.0 as x86_64 OVA virtual appliance and software update packages
  * More details at https://github.com/42ity/release-note/blob/release/IPM-2.3.0/ipm/2.2.0.md
- November 11th, 2020: Released IPM2 Editions service pack version 2.1.0-2 as x86_64 OVA virtual appliance and software update packages
- August 3rd, 2020: Released IPM2 Editions service pack version 2.1.0-1 as x86_64 OVA virtual appliance and software update packages
- June 24th, 2020: Previously marketed IPC3000 hardware appliances officially discontinued due to original device model EOL; existing deployments with IPM Infra supported with a migration path into IPM2
- June 11th, 2020: Released IPM2 Editions version 2.1.0 as x86_64 OVA virtual appliance and software update packages
- October 24th, 2019: Released IPM2 Editions version 2.0.1 as x86_64 OVA virtual appliance and software update packages
- September 23rd, 2019: Released IPM2 Editions version 2.0.0 as x86_64 OVA virtual appliance and software update packages
- April 8th, 2019: Updated firmware and software for the Intelligent Power Controller appliance, built from 42ITy(TM) source-code, was released as Eaton IPM Infra version 1.5.0, and introducing officially supported builds of x86_64 OVA virtual appliances.
- October 25th, 2018: Updated firmware and software for the Intelligent Power Controller appliance, built from 42ITy(TM) source-code, was released as Eaton IPM Infra version 1.4.2.
- September 24th, 2018: Updated firmware and software for the Intelligent Power Controller appliance, built from 42ITy(TM) source-code, was released and made generally downloadable at link:http://www.eaton.eu/ipminfrastructure[Eaton IPM Infra version 1.4.1].
- July 11th, 2018: Updated firmware and software for the Intelligent Power Controller appliance, built from 42ITy(TM) source-code, was released as Eaton IPM Infra version 1.4.0.
- January 25th, 2018: Updated firmware and software for the Intelligent Power Controller appliance, built from 42ITy(TM) source-code, was released as Eaton IPM Infra version 1.3.0.
- July 31st, 2017: Updated firmware and software for the Intelligent Power Controller appliance, built from 42ITy(TM) source-code, was released and made generally downloadable at link:http://www.eaton.eu/ipminfrastructure[Eaton IPM Infra version 1.2.0].
- February 8th, 2017: 42ITy(TM) source-code and updated website availability.
- October 5th, 2016: Initial announcement of 42ITy(TM) availability.
- October 5th, 2016: Initial announcement of link:http://www.eaton.eu/ipminfrastructure[Eaton Intelligent Power Management Infrastructure and Intelligent Power Controller] availability.
